import { GameDefinition } from '../types';

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'wheel',
    slug: 'roleta-premiada',
    name: 'Roleta Premiada',
    category: 'Sorte',
    description: 'Gire a roleta de alta fidelidade e teste sua sorte para conquistar prêmios instantâneos e descontos exclusivos da marca.',
    icon: 'Disc',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-amber-500 via-orange-600 to-red-600',
  },
  {
    id: 'quiz',
    slug: 'quiz-interativo',
    name: 'Quiz da Marca',
    category: 'Conhecimento',
    description: 'Responda perguntas dinâmicas sobre lançamentos e diferenciais com botões touch gigantes e cronômetro regressivo.',
    icon: 'HelpCircle',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-blue-600 via-indigo-600 to-violet-700',
  },
  {
    id: 'target',
    slug: 'caca-alvos',
    name: 'Caça aos Alvos',
    category: 'Reflexo',
    description: 'Toque rápido nos alvos da campanha que surgem na tela antes que desapareçam. Teste supremo de reflexo no totem.',
    icon: 'Target',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-rose-500 via-pink-600 to-red-600',
  },
  {
    id: 'memory',
    slug: 'jogo-memoria',
    name: 'Jogo da Memória',
    category: 'Raciocínio',
    description: 'Vire as cartas e encontre os pares dos veículos e produtos da campanha com flip 3D e contagem de movimentos.',
    icon: 'Grid',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-emerald-500 via-teal-600 to-cyan-700',
  },
  {
    id: 'catcher',
    slug: 'chuva-brindes',
    name: 'Chuva de Brindes',
    category: 'Agilidade',
    description: 'Arraste a cesta/veículo no totem com o dedo para pegar itens promocionais que caem e desvie dos obstáculos.',
    icon: 'ShoppingBag',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-purple-600 via-fuchsia-600 to-pink-600',
  },
  {
    id: 'speed',
    slug: 'arrancada-turbo',
    name: 'Arrancada Turbo',
    category: 'Ação',
    description: 'Toque freneticamente no pedal touch na largada para atingir o tempo recorde de 0 a 100 km/h na pista.',
    icon: 'Gauge',
    estimatedTime: '20 seg',
    difficulty: 'Fácil',
    previewBg: 'from-red-600 via-amber-500 to-yellow-500',
  },
  {
    id: 'safe',
    slug: 'desafio-cofre',
    name: 'Desafio do Cofre',
    category: 'Mistério',
    description: 'Gire a trava de alta segurança ou encontre a combinação correta para abrir o cofre de brindes da ativação.',
    icon: 'Lock',
    estimatedTime: '40 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-600 via-yellow-600 to-orange-700',
  },
  {
    id: 'genius',
    slug: 'sequencia-genius',
    name: 'Sequência Luminosa',
    category: 'Memória',
    description: 'Memorize e reproduza a sequência crescente de luzes e sons nos botões gigantes do totem sem errar.',
    icon: 'Sparkles',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-cyan-500 via-blue-600 to-indigo-700',
  },
  {
    id: 'puzzle',
    slug: 'puzzle-deslizante',
    name: 'Quebra-Cabeça Rápido',
    category: 'Lógica',
    description: 'Deslize as peças no grid com toque tátil para montar a imagem do veículo destaque da campanha no menor tempo.',
    icon: 'Puzzle',
    estimatedTime: '1-2 min',
    difficulty: 'Difícil',
    previewBg: 'from-teal-500 via-emerald-600 to-cyan-600',
  },
  {
    id: 'balloon',
    slug: 'estoura-baloes',
    name: 'Estoura Balões',
    category: 'Casual',
    description: 'Toque para estourar o maior número de balões coloridos subindo pelo totem antes que escapem para o topo.',
    icon: 'Zap',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-orange-500 via-rose-500 to-pink-500',
  },
];
