import { GameDefinition } from '../types';

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'wheel',
    slug: 'roleta-premiada',
    name: 'Roleta Premiada',
    category: 'Sorte',
    description: 'Gire a roleta de alta fidelidade e teste sua sorte para conquistar prêmios instantâneos e descontos exclusivos da marca.',
    icon: 'Disc',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-amber-500 via-orange-600 to-red-600',
  },
  {
    id: 'quiz',
    slug: 'quiz-interativo',
    name: 'Quiz da Marca',
    category: 'Conhecimento',
    description: 'Responda perguntas dinâmicas sobre lançamentos e diferenciais com botões touch gigantes e cronômetro regressivo.',
    icon: 'HelpCircle',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-blue-600 via-indigo-600 to-violet-700',
  },
  {
    id: 'target',
    slug: 'caca-alvos',
    name: 'Caça aos Alvos',
    category: 'Reflexo',
    description: 'Toque rápido nos alvos da campanha que surgem na tela antes que desapareçam. Teste supremo de reflexo no totem.',
    icon: 'Target',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-rose-500 via-pink-600 to-red-600',
  },
  {
    id: 'memory',
    slug: 'jogo-memoria',
    name: 'Jogo da Memória',
    category: 'Raciocínio',
    description: 'Vire as cartas e encontre os pares dos veículos e produtos da campanha com flip 3D e contagem de movimentos.',
    icon: 'Grid',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-emerald-500 via-teal-600 to-cyan-700',
  },
  {
    id: 'catcher',
    slug: 'chuva-brindes',
    name: 'Chuva de Brindes',
    category: 'Agilidade',
    description: 'Arraste a cesta/veículo no totem com o dedo para pegar itens promocionais que caem e desvie dos obstáculos.',
    icon: 'ShoppingBag',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-purple-600 via-fuchsia-600 to-pink-600',
  },
  {
    id: 'speed',
    slug: 'arrancada-turbo',
    name: 'Arrancada Turbo',
    category: 'Ação',
    description: 'Toque freneticamente no pedal touch na largada para atingir o tempo recorde de 0 a 100 km/h na pista.',
    icon: 'Gauge',
    estimatedTime: '20 seg',
    difficulty: 'Fácil',
    previewBg: 'from-red-600 via-amber-500 to-yellow-500',
  },
  {
    id: 'safe',
    slug: 'desafio-cofre',
    name: 'Desafio do Cofre',
    category: 'Mistério',
    description: 'Gire a trava de alta segurança ou encontre a combinação correta para abrir o cofre de brindes da ativação.',
    icon: 'Lock',
    estimatedTime: '40 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-600 via-yellow-600 to-orange-700',
  },
  {
    id: 'genius',
    slug: 'sequencia-genius',
    name: 'Sequência Luminosa',
    category: 'Memória',
    description: 'Memorize e reproduza a sequência crescente de luzes e sons nos botões gigantes do totem sem errar.',
    icon: 'Sparkles',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-cyan-500 via-blue-600 to-indigo-700',
  },
  {
    id: 'puzzle',
    slug: 'puzzle-deslizante',
    name: 'Quebra-Cabeça Rápido',
    category: 'Lógica',
    description: 'Deslize as peças no grid com toque tátil para montar a imagem do veículo destaque da campanha no menor tempo.',
    icon: 'Puzzle',
    estimatedTime: '1-2 min',
    difficulty: 'Difícil',
    previewBg: 'from-teal-500 via-emerald-600 to-cyan-600',
  },
  {
    id: 'balloon',
    slug: 'estoura-baloes',
    name: 'Estoura Balões',
    category: 'Casual',
    description: 'Toque para estourar o maior número de balões coloridos subindo pelo totem antes que escapem para o topo.',
    icon: 'Zap',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-orange-500 via-rose-500 to-pink-500',
  },
  {
    id: 'wordsearch',
    slug: 'caca-palavras',
    name: 'Caça-Palavras',
    category: 'Atenção',
    description: 'Encontre palavras de segurança e termos da campanha no grid de letras.',
    icon: 'Search',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-amber-500 via-yellow-600 to-amber-700',
  },
  {
    id: 'hangman',
    slug: 'jogo-da-forca',
    name: 'Jogo da Forca',
    category: 'Palavras',
    description: 'Adivinhe palavras temáticas tocando no teclado touch antes de esgotar as chances.',
    icon: 'PenTool',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-emerald-500 via-green-600 to-teal-700',
  },
  {
    id: 'truefalse',
    slug: 'verdadeiro-ou-falso',
    name: 'Verdadeiro ou Falso',
    category: 'Julgamento',
    description: 'Julgue afirmações sobre segurança e normas contra o relógio em ritmo acelerado.',
    icon: 'ThumbsUp',
    estimatedTime: '40 seg',
    difficulty: 'Fácil',
    previewBg: 'from-blue-500 via-indigo-600 to-sky-600',
  },
  {
    id: 'complete_phrase',
    slug: 'complete-a-frase',
    name: 'Complete a Frase',
    category: 'Linguagem',
    description: 'Preencha a palavra que falta nas regras e procedimentos de segurança.',
    icon: 'Type',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-fuchsia-500 via-purple-600 to-pink-600',
  },
  {
    id: 'correct_order',
    slug: 'ordem-correta',
    name: 'Ordem Correta',
    category: 'Processos',
    description: 'Coloque procedimentos e passos de segurança na ordem certa.',
    icon: 'ListOrdered',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-teal-500 via-emerald-600 to-cyan-700',
  },
  {
    id: 'speed_trivia',
    slug: 'trivia-rapida',
    name: 'Trivia Rápida',
    category: 'Agilidade',
    description: 'Responda perguntas dinâmicas contra o relógio em modo relâmpago! ⚡',
    icon: 'Zap',
    estimatedTime: '30 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-500 via-orange-500 to-yellow-600',
  },
  {
    id: 'connect_pairs',
    slug: 'conecte-os-pares',
    name: 'Conecte os Pares',
    category: 'Associação',
    description: 'Conecte itens correspondentes entre duas colunas de conceitos e proteções.',
    icon: 'Link',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-sky-500 via-blue-600 to-indigo-700',
  },
  {
    id: 'spot_error',
    slug: 'encontre-o-erro',
    name: 'Encontre o Erro',
    category: 'Percepção',
    description: 'Identifique irregularidades e situações de risco nos cenários da operação.',
    icon: 'AlertTriangle',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-amber-600 via-orange-600 to-red-600',
  },
  {
    id: 'map_epi',
    slug: 'mapa-epi',
    name: 'Mapa + EPI',
    category: 'EPIs',
    description: 'Arraste e posicione os EPIs e proteções adequadas para cada setor de trabalho.',
    icon: 'MapPin',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-rose-600 via-red-600 to-orange-600',
  },
];
