import { GameDefinition } from '../types';

export interface GameCategoryMeta {
  id: string;
  name: string;
  shortName: string;
  icon: string;
  description: string;
  badgeColor: string;
  glowColor: string;
}

export const GAME_CATEGORIES: GameCategoryMeta[] = [
  {
    id: 'quizzes',
    name: 'Quizzes & Perguntas',
    shortName: 'Quizzes',
    icon: 'HelpCircle',
    description: 'Desafios de conhecimento, perguntas rápidas e testes de verdadeiro ou falso.',
    badgeColor: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    glowColor: '#3B82F6',
  },
  {
    id: 'agility',
    name: 'Agilidade & Reflexo',
    shortName: 'Agilidade',
    icon: 'Zap',
    description: 'Jogos dinâmicos de velocidade, reflexos e precisão rápida na tela touch.',
    badgeColor: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    glowColor: '#F59E0B',
  },
  {
    id: 'logic',
    name: 'Raciocínio & Memória',
    shortName: 'Raciocínio',
    icon: 'Brain',
    description: 'Testes de memorização, sequências lógicas e combinação de peças.',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
    glowColor: '#10B981',
  },
  {
    id: 'words',
    name: 'Palavras & Linguagem',
    shortName: 'Palavras',
    icon: 'Type',
    description: 'Jogos de vocabulário, adivinhação de palavras e caça-palavras.',
    badgeColor: 'bg-purple-500/15 text-purple-400 border-purple-500/30',
    glowColor: '#A855F7',
  },
  {
    id: 'luck',
    name: 'Sorte & Recompensas',
    shortName: 'Sorte',
    icon: 'Disc',
    description: 'Ativações de brindes instantâneos, roletas e segredos premiados.',
    badgeColor: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
    glowColor: '#F43F5E',
  },
  {
    id: 'safety',
    name: 'Segurança & Treinamento',
    shortName: 'Segurança',
    icon: 'Shield',
    description: 'Simulações de procedimentos, normas de segurança e mapeamento de EPIs.',
    badgeColor: 'bg-teal-500/15 text-teal-400 border-teal-500/30',
    glowColor: '#14B8A6',
  },
  {
    id: 'math',
    name: 'Cálculo & Lógica Numérica',
    shortName: 'Cálculo',
    icon: 'Calculator',
    description: 'Desafios matemáticos relâmpago, estimativas numéricas e raciocínio quantitativo.',
    badgeColor: 'bg-indigo-500/15 text-indigo-400 border-indigo-500/30',
    glowColor: '#6366F1',
  },
  {
    id: 'precision',
    name: 'Precisão & Coordenação',
    shortName: 'Precisão',
    icon: 'Target',
    description: 'Controle de tempo, reflexo do semáforo de largada e pontaria ao alvo.',
    badgeColor: 'bg-orange-500/15 text-orange-400 border-orange-500/30',
    glowColor: '#F97316',
  },
];

export const GAMES_CATALOG: GameDefinition[] = [
  // 1. Quizzes & Perguntas
  {
    id: 'quiz',
    slug: 'quiz-interativo',
    name: 'Quiz',
    category: 'Quizzes & Perguntas',
    categoryId: 'quizzes',
    description: 'Responda perguntas dinâmicas sobre lançamentos e diferenciais com botões touch gigantes e cronômetro regressivo.',
    icon: 'HelpCircle',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-blue-600 via-indigo-600 to-violet-700',
  },
  {
    id: 'speed_trivia',
    slug: 'trivia-rapida',
    name: 'Trivia Rápida',
    category: 'Quizzes & Perguntas',
    categoryId: 'quizzes',
    description: 'Responda perguntas dinâmicas contra o relógio em modo relâmpago! ⚡',
    icon: 'Zap',
    estimatedTime: '30 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-500 via-orange-500 to-yellow-600',
  },
  {
    id: 'truefalse',
    slug: 'verdadeiro-ou-falso',
    name: 'Verdadeiro ou Falso',
    category: 'Quizzes & Perguntas',
    categoryId: 'quizzes',
    description: 'Julgue afirmações sobre segurança e normas contra o relógio em ritmo acelerado.',
    icon: 'ThumbsUp',
    estimatedTime: '40 seg',
    difficulty: 'Fácil',
    previewBg: 'from-blue-500 via-indigo-600 to-sky-600',
  },
  {
    id: 'complete_phrase',
    slug: 'complete-a-frase',
    name: 'Complete a Frase',
    category: 'Quizzes & Perguntas',
    categoryId: 'quizzes',
    description: 'Preencha a palavra que falta nas regras e procedimentos de segurança.',
    icon: 'Type',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-fuchsia-500 via-purple-600 to-pink-600',
  },

  // 2. Agilidade & Reflexo
  {
    id: 'target',
    slug: 'caca-alvos',
    name: 'Caça aos Alvos',
    category: 'Agilidade & Reflexo',
    categoryId: 'agility',
    description: 'Toque rápido nos alvos da campanha que surgem na tela antes que desapareçam. Teste supremo de reflexo no totem.',
    icon: 'Target',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-rose-500 via-pink-600 to-red-600',
  },
  {
    id: 'catcher',
    slug: 'chuva-brindes',
    name: 'Chuva de Brindes',
    category: 'Agilidade & Reflexo',
    categoryId: 'agility',
    description: 'Arraste a cesta/veículo no totem com o dedo para pegar itens promocionais que caem e desvie dos obstáculos.',
    icon: 'ShoppingBag',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-purple-600 via-fuchsia-600 to-pink-600',
  },
  {
    id: 'speed',
    slug: 'arrancada-turbo',
    name: 'Arrancada Turbo',
    category: 'Agilidade & Reflexo',
    categoryId: 'agility',
    description: 'Toque freneticamente no pedal touch na largada para atingir o tempo recorde de 0 a 100 km/h na pista.',
    icon: 'Gauge',
    estimatedTime: '20 seg',
    difficulty: 'Fácil',
    previewBg: 'from-red-600 via-amber-500 to-yellow-500',
  },
  {
    id: 'balloon',
    slug: 'estoura-baloes',
    name: 'Estoura Balões',
    category: 'Agilidade & Reflexo',
    categoryId: 'agility',
    description: 'Toque para estourar o maior número de balões coloridos subindo pelo totem antes que escapem para o topo.',
    icon: 'Zap',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-orange-500 via-rose-500 to-pink-500',
  },

  // 3. Raciocínio & Memória
  {
    id: 'memory',
    slug: 'jogo-memoria',
    name: 'Jogo da Memória',
    category: 'Raciocínio & Memória',
    categoryId: 'logic',
    description: 'Vire as cartas e encontre os pares dos veículos e produtos da campanha com flip 3D e contagem de movimentos.',
    icon: 'Grid',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-emerald-500 via-teal-600 to-cyan-700',
  },
  {
    id: 'genius',
    slug: 'sequencia-genius',
    name: 'Sequência Luminosa',
    category: 'Raciocínio & Memória',
    categoryId: 'logic',
    description: 'Memorize e reproduza a sequência crescente de luzes e sons nos botões gigantes do totem sem errar.',
    icon: 'Sparkles',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-cyan-500 via-blue-600 to-indigo-700',
  },
  {
    id: 'puzzle',
    slug: 'puzzle-deslizante',
    name: 'Quebra-Cabeça Rápido',
    category: 'Raciocínio & Memória',
    categoryId: 'logic',
    description: 'Deslize as peças no grid com toque tátil para montar a imagem do veículo destaque da campanha no menor tempo.',
    icon: 'Puzzle',
    estimatedTime: '1-2 min',
    difficulty: 'Difícil',
    previewBg: 'from-teal-500 via-emerald-600 to-cyan-600',
  },
  {
    id: 'connect_pairs',
    slug: 'conecte-os-pares',
    name: 'Conecte os Pares',
    category: 'Raciocínio & Memória',
    categoryId: 'logic',
    description: 'Conecte itens correspondentes entre duas colunas de conceitos e proteções.',
    icon: 'Link',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-sky-500 via-blue-600 to-indigo-700',
  },

  // 4. Palavras & Linguagem
  {
    id: 'wordsearch',
    slug: 'caca-palavras',
    name: 'Caça-Palavras',
    category: 'Palavras & Linguagem',
    categoryId: 'words',
    description: 'Encontre palavras de segurança e termos da campanha no grid de letras.',
    icon: 'Search',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-amber-500 via-yellow-600 to-amber-700',
  },
  {
    id: 'hangman',
    slug: 'jogo-da-forca',
    name: 'Jogo da Forca',
    category: 'Palavras & Linguagem',
    categoryId: 'words',
    description: 'Adivinhe palavras temáticas tocando no teclado touch antes de esgotar as chances.',
    icon: 'PenTool',
    estimatedTime: '45 seg',
    difficulty: 'Médio',
    previewBg: 'from-emerald-500 via-green-600 to-teal-700',
  },

  // 5. Sorte & Recompensas
  {
    id: 'wheel',
    slug: 'roleta-premiada',
    name: 'Roleta Premiada',
    category: 'Sorte & Recompensas',
    categoryId: 'luck',
    description: 'Gire a roleta de alta fidelidade e teste sua sorte para conquistar prêmios instantâneos e descontos exclusivos da marca.',
    icon: 'Disc',
    estimatedTime: '30 seg',
    difficulty: 'Fácil',
    previewBg: 'from-amber-500 via-orange-600 to-red-600',
  },
  {
    id: 'safe',
    slug: 'desafio-cofre',
    name: 'Desafio do Cofre',
    category: 'Sorte & Recompensas',
    categoryId: 'luck',
    description: 'Gire a trava de alta segurança ou encontre a combinação correta para abrir o cofre de brindes da ativação.',
    icon: 'Lock',
    estimatedTime: '40 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-600 via-yellow-600 to-orange-700',
  },

  // 6. Segurança & Treinamento
  {
    id: 'map_epi',
    slug: 'mapa-epi',
    name: 'Mapa + EPI',
    category: 'Segurança & Treinamento',
    categoryId: 'safety',
    description: 'Arraste e posicione os EPIs e proteções adequadas para cada setor de trabalho.',
    icon: 'MapPin',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-rose-600 via-red-600 to-orange-600',
  },
  {
    id: 'spot_error',
    slug: 'encontre-o-erro',
    name: 'Encontre o Erro',
    category: 'Segurança & Treinamento',
    categoryId: 'safety',
    description: 'Identifique irregularidades e situações de risco nos cenários da operação.',
    icon: 'AlertTriangle',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-amber-600 via-orange-600 to-red-600',
  },
  {
    id: 'correct_order',
    slug: 'ordem-correta',
    name: 'Ordem Correta',
    category: 'Segurança & Treinamento',
    categoryId: 'safety',
    description: 'Coloque procedimentos e passos de segurança na ordem certa.',
    icon: 'ListOrdered',
    estimatedTime: '1 min',
    difficulty: 'Médio',
    previewBg: 'from-teal-500 via-emerald-600 to-cyan-700',
  },

  // 7. [NOVA] Cálculo & Lógica Numérica
  {
    id: 'math_blitz',
    slug: 'calculo-turbo',
    name: 'Cálculo Turbo',
    category: 'Cálculo & Lógica Numérica',
    categoryId: 'math',
    description: 'Resolva operações e metas dinâmicas com botões touch gigantes em ritmo acelerado contra o relógio.',
    icon: 'Calculator',
    estimatedTime: '30 seg',
    difficulty: 'Médio',
    previewBg: 'from-indigo-600 via-blue-600 to-cyan-600',
  },
  {
    id: 'higher_lower',
    slug: 'maior-ou-menor',
    name: 'Maior ou Menor',
    category: 'Cálculo & Lógica Numérica',
    categoryId: 'math',
    description: 'Adivinhe se o próximo número ou métrica da campanha será Maior ou Menor. Mantenha a sequência sem errar!',
    icon: 'TrendingUp',
    estimatedTime: '45 seg',
    difficulty: 'Fácil',
    previewBg: 'from-blue-600 via-indigo-700 to-violet-800',
  },

  // 8. [NOVA] Precisão & Coordenação
  {
    id: 'reaction_time',
    slug: 'reflexo-semaforo',
    name: 'Reflexo do Semáforo',
    category: 'Precisão & Coordenação',
    categoryId: 'precision',
    description: 'Aguarde as 5 luzes vermelhas se apagarem e toque instantaneamente! Teste de milissegundos para pilotos.',
    icon: 'Gauge',
    estimatedTime: '30 seg',
    difficulty: 'Médio',
    previewBg: 'from-red-600 via-orange-600 to-amber-600',
  },
  {
    id: 'bullseye',
    slug: 'mira-certa',
    name: 'Mira Certa',
    category: 'Precisão & Coordenação',
    categoryId: 'precision',
    description: 'Toque no momento exato em que a mira oscilante cruzar o centro do alvo para acertar o Bullseye de pontuação máxima!',
    icon: 'Crosshair',
    estimatedTime: '40 seg',
    difficulty: 'Médio',
    previewBg: 'from-amber-500 via-orange-600 to-rose-600',
  },
];
